name: Update Online Feed

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:
  push:
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install CSV parser
        run: npm install csv-parser

      - name: Run generator script
        run: |
          node generate-rss.js


      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html feed.xml
          git commit -m "🔄 Auto-update index.html from Google Sheet" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/latamprompt/Online-Feed.git

