name: Build RSS from Google Sheets

on:
  # Manual trigger for testing
  workflow_dispatch:
  # OPTIONAL: keep or tweak your schedule (every 30 min here)
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Download your published CSV to a local file Feed.csv
      - name: Download CSV
        run: |
          CSV_URL="https://docs.google.com/spreadsheets/d/e/2PACX-1vSyhDvRQE6Uo75KjBrUyd9v_NZrQERqupl1LxS7sD50WoTKHVBMbs42x_7ne7I3JK_QJHlHa_rckK0-/pub?gid=477208386&single=true&output=csv"
          curl -fL "$CSV_URL" -o Feed.csv
          echo "Downloaded CSV to $(pwd)/Feed.csv"
      
      # Build the RSS (validates XML too)
      - name: Build RSS
        run: |
          node generate-rss.js --in Feed.csv --out feed.xml --validate-xml

      # Commit only if feed.xml changed
      - name: Commit feed if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet -- feed.xml; then
            git add feed.xml
            git commit -m "[rss] update feed.xml"
            git push
          else
            echo "No changes to feed.xml"
          fi
